"""Initial migration.

Revision ID: 85b58bd15855
Revises: 
Create Date: 2024-05-16 20:09:17.582189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85b58bd15855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('contrasena', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('estancias_usuarios_hoteles')
    op.drop_table('usuarios_restaurantes_platos')
    op.drop_table('degustadores')
    op.drop_table('resenas_degustadores')
    op.drop_table('usuarios')
    op.drop_table('platos')
    op.drop_table('tours_restaurantes')
    op.drop_table('resenas')
    op.drop_table('hoteles')
    op.drop_table('restaurantes')
    op.drop_table('guias_turisticos')
    op.drop_table('degustadores_restaurantes')
    op.drop_table('resenas_hoteles')
    op.drop_table('restaurantes_platos')
    op.drop_table('tours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tours',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duracion', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('guia_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guia_id'], ['guias_turisticos.id'], name='tours_guia_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], name='tours_hotel_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tours_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('restaurantes_platos',
    sa.Column('restaurante_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plato_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], name='restaurantes_platos_plato_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], name='restaurantes_platos_restaurante_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('restaurante_id', 'plato_id', name='restaurantes_platos_pkey')
    )
    op.create_table('resenas_hoteles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calificacion', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], name='resenas_hoteles_hotel_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='resenas_hoteles_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resenas_hoteles_pkey')
    )
    op.create_table('degustadores_restaurantes',
    sa.Column('degustador_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('restaurante_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha_asignacion', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['degustador_id'], ['degustadores.id'], name='degustadores_restaurantes_degustador_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], name='degustadores_restaurantes_restaurante_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('degustador_id', 'restaurante_id', name='degustadores_restaurantes_pkey')
    )
    op.create_table('guias_turisticos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idiomas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('licencia', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('especializacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('disponibilidad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calificacion', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('biografia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='guias_turisticos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('restaurantes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('localidad', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sitio_web', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('capacidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('horario', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='restaurantes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('hoteles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sitio_web', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('categoría', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('calificación', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hoteles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('resenas',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('tour_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calificacion', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name='resenas_tour_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='resenas_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resenas_pkey')
    )
    op.create_table('tours_restaurantes',
    sa.Column('tour_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('restaurante_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], name='tours_restaurantes_restaurante_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name='tours_restaurantes_tour_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tour_id', 'restaurante_id', name='tours_restaurantes_pkey')
    )
    op.create_table('platos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('restaurante_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], name='platos_restaurante_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='platos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('localidad', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('contrasena', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('restaurante_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('hotel_actual', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_actual'], ['hoteles.id'], name='usuarios_hotel_actual_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], name='usuarios_restaurante_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('resenas_degustadores',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('degustador_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('plato_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('restaurante_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calificacion', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['degustador_id'], ['degustadores.id'], name='resenas_degustadores_degustador_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], name='resenas_degustadores_plato_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], name='resenas_degustadores_restaurante_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resenas_degustadores_pkey')
    )
    op.create_table('degustadores',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('especializacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('biografia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='degustadores_usuario_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='degustadores_pkey')
    )
    op.create_table('usuarios_restaurantes_platos',
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('restaurante_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plato_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], name='usuarios_restaurantes_platos_plato_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], name='usuarios_restaurantes_platos_restaurante_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='usuarios_restaurantes_platos_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'restaurante_id', 'plato_id', name='usuarios_restaurantes_platos_pkey')
    )
    op.create_table('estancias_usuarios_hoteles',
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha_entrada', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_salida', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], name='estancias_usuarios_hoteles_hotel_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='estancias_usuarios_hoteles_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'hotel_id', 'fecha_entrada', name='estancias_usuarios_hoteles_pkey')
    )
    op.drop_table('usuario')
    # ### end Alembic commands ###
